### ISSUE TITLE
Support Generation/ObservedGeneration

### ISSUE THREAD

**Issue by ash2k** [atlassian/smith#102]
Per [recommendation on writing controllers](https://github.com/kubernetes/community/blob/master/contributors/devel/controllers.md) Bundle object should have ObservedGeneration in it's status. Some discussions about it:
- https://github.com/kubernetes/kubernetes/issues/7328
- https://github.com/kubernetes/features/issues/95#issuecomment-302946176

It is blocked on splitting spec/status for CustomResources (item in list https://github.com/kubernetes/features/issues/95). Because Smith cannot update status without also bumping up metadata.generation (is it even incremented automatically in 1.7?).

**Comment by nilebox** [comment]
I believe this issue is unblocked now since https://github.com/kubernetes/kubernetes/pull/55168 has just been merged 🎉 
This feature will be supported in the next Kubernetes release - 1.10.
