### ISSUE TITLE
Consider using `go_image` to reduce boilerplate.

### ISSUE THREAD

**Issue by mattmoor** [atlassian/smith#165]
See here: https://github.com/atlassian/smith/blob/63624b47d77f48cae9379528ead25d3fea00e9b5/cmd/smith/BUILD.bazel#L20-L32

This can use [this](https://github.com/bazelbuild/rules_docker#go_image):
```python
  go_image( 
     name = "smith", 
     embed = [":go_default_library"], 
     importpath = "github.com/atlassian/smith/cmd/smith", 
     visibility = ["//visibility:public"], 
 ) 
```

(the goal is to make containerizing as simple as `s/lang_binary/lang_image/`)

You might also TAL at `rules_k8s`, feel free to reach out if you have any problems.

**Comment by ash2k** [comment]
Hey, thanks for suggestion. I new about these extra rules but I haven't tried them. I have just tried and here is what I found:
- it is cool that I don't need to maintain distroless base layer sha
- Gazelle still generates `go_binary` rule and if `go_image` has `name=smith` then they conflict.
- If I change `name=smith_container` on `go_image` to avoid the conflict then it works but now I have two rules - just like before :)
- I need an ability to run the binary. I usually build it and then run it (I don't use `bazel run` for this). This becomes `bazel-bin/cmd/smith/smith_container.binary` vs `bazel-bin/cmd/smith/smith`. It's a bit uglier and, which is more important, more magical - it is not obvious what is that `.binary` and there is no way to know it exists without looking at the rule implementation.

So given the above I think it is unlikely I'll use it unless there is a way to improve the user experience somehow.

**Comment by mattmoor** [comment]
Yeah, I have a bug open against Gazelle.  This came up [here](https://github.com/kubernetes/test-infra/pull/4929#pullrequestreview-80041244) so I may augment the surface of language rules that don't benefit from layering to also accept the binary target directly.

(to elaborate a bit) For Go there is less benefit than with languages like Python and Java where we can intelligently factor layers (you can see some commentary on this [here](https://github.com/bazelbuild/rules_docker/issues/232) and [here](https://github.com/bazelbuild/rules_k8s/blob/master/examples/hellogrpc/py/server/BUILD#L24-L28)).  Eventually I'd like to make this more intelligent and less manual.

I'll open an FR on `rules_docker` to track this for now.

> it is cool that I don't need to maintain distroless base layer sha

Even if you don't use `go_image`, you can get the benefit of this by using the following symbol for your `base` image: https://github.com/bazelbuild/rules_docker/blob/master/go/image.bzl#L59-L64  This has the benefit of putting `busybox` into containers built with `-c dbg` :)


Mostly I wanted to reach out and make sure you were aware of the option.  If you run into any problems, please don't hesitate to reach out.

**Comment by mattmoor** [comment]
I think [this](https://github.com/bazelbuild/rules_docker/pull/252) should get you what you want.

Let me know if you run into any trouble using it.
