### ISSUE TITLE
JsonPath execute error on bundle references

### ISSUE THREAD

**Issue by ychen-atlassian** [atlassian/smith#255]
```
invalid reference at "spec#parameters#iamInstanceProfile": failed
        to process JsonPath reference notifier--notifier--iamrole--binding:bindsecret#Data.InstanceProfile#"exampleIamInstanceProfile":
        JsonPath execute error: InstanceProfile#"exampleIamInstanceProfile" is not
        found
```

**Comment by ychen-atlassian** [comment]
Initially I thought "Data" was incorrect because it didn't match the case sensitive "data" field in the JSON, but I fixed that and the problem is still there.

**Comment by wryun** [comment]
That's super-weird. It looks like it's not parsing the 'examples' properly. Err, oops.

**Comment by wryun** [comment]
Are you sure you've run dep ensure? This would be the behaviour if you had an old version of Smith.

**Comment by wryun** [comment]
I can't duplicate this problem. Seems to resolve fine for me against the current master (deployed to cluster).
