### ISSUE TITLE
cleanup functions don't work properly if externalID is changed

### ISSUE THREAD

**Issue by wryun** [atlassian/smith#304]
instanceSpec.Spec.ExternalID = instanceActual.Spec.ExternalID

^ bad logic - should copy only if Spec is empty. Otherwise, make sure it can handle error properly from Service Catalog on clash (or just detect here?).

**Comment by amckague** [comment]
Most likely the cleanup logic should look like this:

For class:
* Check immutability of the class things (not plan things) if empty, use whatever one they had previously
* If not empty and they don't match, error

For plans:
* Error if they go from id->name or name->id if using names for class, must use name for plans (same with IDs)
* take the user's version
