### ISSUE TITLE
Remove reference to dep in README

### ISSUE THREAD

**Issue by rodrigc** [atlassian/smith#438]
https://github.com/atlassian/smith/blob/master/README.md#building-testing-and-running
still mentions `dep`, but looks like `smith` has been converted to go modules (nicely done by the way).

Since you have converted to go modules completely, you might want to mention the minimum version of go required.  I'm guessing go1.11+ will probably work,
while go1.10 and lower will defniitely not work.

**Comment by ash2k** [comment]
Thanks!
